Feature/knt1 391 push version
konstellation-io/kai pull request #107
Opened 2023-09-14 08:54 UTC by JYisus

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-09-14 14:12 UTC, kafkaphoenix submitted a review, later dismissed

2023-09-14 14:24 UTC, alexrodfe commented on engine/admin-api/adapter/repository/mongodb/versionrepository/repository.go
> +func (r *VersionRepoMongoDB) Update(productID string, updatedVersion *entity.Version) error {
imo I'd have this "updatedVersion" as versionToUpdate or something similar that tells this is the version that is going to be updated, not that it has been updated

2023-09-14 14:32 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/create_test.go
> +	//versionService   *mocks.MockVersionService
watch out unused variable

2023-09-14 14:32 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/create_test.go
> +				//Stream:    "",
ditto

2023-09-14 14:35 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/handler_test.go
> -import (
why is everything commented?

2023-09-14 14:36 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/handler_test.go
> -import (
this file is deleted in the start version pr btw, in favor to a new version test suite

2023-09-14 14:39 UTC, alexrodfe commented on engine/admin-api/internal/errors/errors.go
>  	ErrCreatingDashboard = errors.New("error creating dashboard")
I believe these two last errors are no longer needed

2023-09-14 14:40 UTC, alexrodfe requested changes
Great, look good
I got a couple of questions

2023-09-14 15:04 UTC, JYisus commented on engine/admin-api/adapter/repository/mongodb/versionrepository/repository.go
> +func (r *VersionRepoMongoDB) Update(productID string, updatedVersion *entity.Version) error {
Well, it is the updated version indeed, but not persisted. I mean, the version already has the changes.

2023-09-14 15:05 UTC, JYisus commented on engine/admin-api/domain/usecase/version/handler_test.go
> -import (
Yep, I was using it as reference, but I forgot to delete it

2023-09-15 11:21 UTC, kafkaphoenix approved these changes

2023-09-15 13:04 UTC, kafkaphoenix approved these changes

2023-09-15 13:19 UTC, alexrodfe approved these changes

2023-09-15 13:20 UTC, merged