Feature/unpublish refactor
konstellation-io/kai pull request #114
Opened 2023-09-21 10:53 UTC by kafkaphoenix

## Description

Refactor unpublish

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-09-21 11:48 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/unpublish.go
>  	if err != nil {
missing registerActionFailed

2023-09-21 11:49 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/unpublish.go
> +	err = h.versionRepo.Update(productID, vers)
this should be non blocking

2023-09-21 11:49 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/unpublish.go
> +	err = h.userActivityInteractor.RegisterUnpublishAction(user.ID, productID, vers, comment)
this also should be non blocking

2023-09-21 11:50 UTC, alexrodfe requested changes
Fantastic, I have some comments to improve logic and follow other file's structure

2023-09-21 14:38 UTC, kafkaphoenix commented on engine/admin-api/domain/usecase/version/unpublish.go
> +	err = h.userActivityInteractor.RegisterUnpublishAction(user.ID, productID, vers, comment)
done

2023-09-21 14:39 UTC, kafkaphoenix commented on engine/admin-api/domain/usecase/version/unpublish.go
>  	if err != nil {
done

2023-09-25 08:54 UTC, alexrodfe submitted a review, later dismissed

2023-09-25 09:03 UTC, alexrodfe approved these changes

2023-09-25 09:06 UTC, merged