feat(k8s-manager): add horizontal pod autoscaler when multiple replicas
konstellation-io/kai pull request #134
Opened 2023-10-06 15:10 UTC by JYisus

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [x] I have created tests for my code changes, and the tests are passing.
- [x] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-10-11 10:20 UTC, alexrodfe commented on engine/k8s-manager/internal/infrastructure/kube/process/create.go
> -			Replicas: pointer.Int32(spec.Process.Replicas),
watchout dead code

2023-10-11 10:20 UTC, alexrodfe commented on engine/k8s-manager/internal/infrastructure/kube/process/create.go
> +		TypeMeta: metav1.TypeMeta{
out of curiosity, why is this important to add?

2023-10-11 10:20 UTC, alexrodfe commented on engine/k8s-manager/internal/infrastructure/kube/process/create.go
> +			//Replicas: pointer.Int32(spec.Process.Replicas),
watchout dead code

2023-10-11 10:24 UTC, alexrodfe commented on engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
> +        replicas: null
is desirable to have null replicas as an example?

2023-10-11 10:25 UTC, alexrodfe requested changes
Great!
I have a couple of questions before proceeding

2023-10-11 10:25 UTC, alexrodfe commented on engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
> +        replicas: null
note: all other changed goldens have changed their replicas to null

2023-10-11 10:49 UTC, dfinteligenz requested changes

2023-10-11 10:49 UTC, dfinteligenz commented on engine/k8s-manager/internal/infrastructure/kube/process/autoscaler.go
> +							AverageUtilization: pointer.Int32(80),
I'd retrieve the average utilization from viper, and set a default value for the property of 80.
This way we can override it with external configuration (env variable or configuration file) if needed.

2023-10-11 10:49 UTC, dfinteligenz commented on engine/k8s-manager/internal/infrastructure/kube/process/create.go
> +		TypeMeta: metav1.TypeMeta{
We thought the Kubernetes API was setting the values automatically, but it wasn't, and when implementing the HPA it was problematic.

2023-10-11 10:49 UTC, dfinteligenz commented on engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
> +        replicas: null
The replicas field on the deployment is not needed anymore.

For upscaling to N replicas, the replica number is defined in the HPA and the HPA is the responsible of upscaling when needed based on the specified metrics.

2023-10-16 15:34 UTC, dfinteligenz approved these changes
Great job!

2023-10-16 15:40 UTC, merged