feat(helm): cleanup chart unused components
konstellation-io/kai pull request #154
Opened 2023-10-25 14:57 UTC by alpiquero

## Description
Removed unused components from the chart
* Mongo-writer
* Mongo-express
* InfluxDB

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [X] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [X] I have updated the documentation accordingly.

2023-10-25 17:34 UTC, dfinteligenz requested changes
We need to maintain the Influx until we do a refactor on Kai

2023-10-25 17:34 UTC, dfinteligenz commented on helm/kai/CHART.md
> -| https://helm.influxdata.com/ | influxdb | 4.8.1 |
The influx repository is still being used in KAI, we need to remove all references before removing the instance from the chart.

2023-10-25 17:35 UTC, dfinteligenz requested changes
We need to maintain the Influx instance until we do the refactor on KAI

2023-10-26 07:44 UTC, alpiquero commented
@dfinteligenz  we will block this PR until API refactors had been completed on this regard

2023-10-26 08:14 UTC, dfinteligenz commented
> @

Ok, set it as Draft then please.

2023-11-20 12:10 UTC, closed without merging