feature: upload images minio
konstellation-io/kai pull request #165
Opened 2023-10-31 09:46 UTC by JYisus

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-10-31 09:58 UTC, kafkaphoenix approved these changes

2023-10-31 10:03 UTC, kafkaphoenix commented on helm/kai/templates/engine/k8s-manager/configmap.yaml
> +  KAI_MINIO_ENDPOINT_URL: "{{ include "minio.fullname" .Subcharts.minio }}:{{ .Values.minio.service.port }}"
in the sdk we are naming this just minio url maybe we can remove endpoint here?

2023-10-31 10:06 UTC, kafkaphoenix commented on engine/k8s-manager/internal/infrastructure/config/viper.go
> +	MinioEndpointKey        = "minio.endpoint"
we don't use region and endpoint for us in sdk is url

2023-10-31 10:07 UTC, kafkaphoenix requested changes
SDK compatibility discussion

2023-10-31 10:32 UTC, kafkaphoenix commented on engine/k8s-manager/internal/infrastructure/config/viper.go
> +	MinioEndpointKey        = "minio.endpoint"
TODO: rename to endpoint in sdk

2023-10-31 10:32 UTC, kafkaphoenix submitted a review, later dismissed

2023-11-02 08:48 UTC, dfinteligenz commented on engine/admin-api/adapter/repository/objectstorage/minio.go
> +}
We should store the images into a subfolder inside the product bucket.

2023-11-02 10:37 UTC, JYisus commented on engine/admin-api/adapter/repository/objectstorage/minio.go
> +}
Yep, since the object name is in the format: registry-name/image:version, the image is stored in a folder with the name of the registry-name

2023-11-02 10:47 UTC, dfinteligenz approved these changes

2023-11-02 10:54 UTC, merged