Feature(nats-manager): delete version key value stores
konstellation-io/kai pull request #177
Opened 2023-11-08 15:39 UTC by alexrodfe

## Description

- Added delete version key value stores endpoint to nats manager
- Used delete kv endpoint in admin-api during version stop
- Added usage of endpoint as compensation action during start

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [X] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-11-08 16:16 UTC, JYisus requested changes

2023-11-08 16:16 UTC, JYisus commented on engine/admin-api/adapter/service/natsmanager/nats_manager_test.go
> +var mockedError = fmt.Errorf("mocked error")
Use errors.New instead of fmt.Errorf if you are not wrapping another error

2023-11-08 16:16 UTC, JYisus commented on engine/nats-manager/internal/manager/delete_kv_stores_test.go
> +		projectKeyValueStore  = "key-store_test-product_v1_0_0"
```suggestion
		versionKeyValueStore  = "key-store_test-product_v1_0_0"
```

2023-11-08 16:23 UTC, alexrodfe commented on engine/nats-manager/internal/manager/delete_kv_stores_test.go
> +		projectKeyValueStore  = "key-store_test-product_v1_0_0"
good catch

2023-11-08 16:23 UTC, alexrodfe commented on engine/admin-api/adapter/service/natsmanager/nats_manager_test.go
> +var mockedError = fmt.Errorf("mocked error")
seems fine by me

2023-11-13 09:15 UTC, kafkaphoenix approved these changes

2023-11-13 18:11 UTC, JYisus approved these changes

2023-11-14 09:45 UTC, merged