fix: delete version in hosts urls when a version is published
konstellation-io/kai pull request #180
Opened 2023-11-13 10:53 UTC by JYisus

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-11-13 11:17 UTC, alexrodfe commented on engine/admin-api/domain/entity/product_test.go
> +	product := testhelpers.NewProductBuilder().Build()
this product should be created WithPublishedVersion

2023-11-13 11:22 UTC, alexrodfe reviewed
Great done!
Just one tip

2023-11-13 12:07 UTC, JYisus commented on engine/admin-api/domain/entity/product_test.go
> +	product := testhelpers.NewProductBuilder().Build()
True, I added the WithPublishedVersion after this test

2023-11-13 13:16 UTC, dfinteligenz approved these changes

2023-11-13 13:16 UTC, dfinteligenz requested changes
There are some tests failing, check them out @JYisus

2023-11-15 14:59 UTC, kafkaphoenix submitted a review, later dismissed

2023-11-15 15:32 UTC, alexrodfe approved these changes

2023-11-17 13:18 UTC, kafkaphoenix approved these changes

2023-11-17 14:42 UTC, alexrodfe approved these changes

2023-11-20 09:20 UTC, dfinteligenz approved these changes

2023-11-20 10:05 UTC, merged