feature(k8s-manager): parse logs correctly from fluent bit to loki
konstellation-io/kai pull request #185
Opened 2023-11-15 15:37 UTC by alexrodfe

## Description

- Fixed app.log volume mount for processes
- Added parser for fluent bit
- Bumped fluent bit to 2.2.0

## Motivation and Context

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-11-16 12:13 UTC, IGZangelcostales submitted a review, later dismissed

2023-11-20 09:21 UTC, JYisus commented on engine/k8s-manager/config.yml
> +baseDomainName: 'local'
We should avoid these changes made by the ide

2023-11-20 09:23 UTC, JYisus requested changes

2023-11-20 09:23 UTC, JYisus commented on engine/k8s-manager/internal/infrastructure/kube/configuration/configmap.go
> +    Host kai-local-loki
This should not be hardcoded, use an env var instead

2023-11-20 09:23 UTC, JYisus commented on engine/k8s-manager/internal/infrastructure/kube/configuration/configmap.go
> +    Port 3100
Same here, use and env var

2023-11-20 09:25 UTC, alpiquero commented on engine/k8s-manager/config.yml
> +baseDomainName: 'local'
I think the `.editorconfig` file can be modified to avoid this and other similar issues.
We can also check our IDE's yaml extensions or plugins

2023-11-20 09:25 UTC, alpiquero submitted a review, later dismissed
LGTM

2023-11-20 10:01 UTC, dfinteligenz requested changes

2023-11-20 12:36 UTC, alexrodfe commented on engine/k8s-manager/config.yml
> +baseDomainName: 'local'
tried adding quote_type = double to the .editorconfig but didn't work
i'll change it manually

2023-11-21 09:49 UTC, kafkaphoenix approved these changes

2023-11-21 15:18 UTC, kafkaphoenix approved these changes

2023-11-21 16:56 UTC, alpiquero approved these changes

2023-11-22 08:02 UTC, dfinteligenz approved these changes

2023-11-22 09:45 UTC, JYisus approved these changes

2023-11-22 09:47 UTC, merged