fix(k8s-manager): add configurable kaniko image
konstellation-io/kai pull request #196
Opened 2023-11-21 13:05 UTC by JYisus

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-11-21 13:06 UTC, kafkaphoenix submitted a review, later dismissed

2023-11-21 13:26 UTC, IGZangelcostales submitted a review, later dismissed

2023-11-21 13:36 UTC, alpiquero requested changes

2023-11-21 13:36 UTC, alpiquero commented on helm/kai/templates/engine/k8s-manager/configmap.yaml
> +  KAI_IMAGE_BUILDER_IMAGE: {{ .Values.k8sManager.imageBuilder.image }}
This should be KAI_IMAGE_BUILDER_IMAGE_REPOSITORY

2023-11-21 13:36 UTC, alpiquero commented on engine/k8s-manager/internal/infrastructure/config/viper.go
>  	viper.RegisterAlias(ImageBuilderImageKey, "IMAGE_BUILDER_IMAGE")
This should be
```
viper.RegisterAlias(ImageBuilderImageKey, "IMAGE_BUILDER_IMAGE_REPOSITORY")
```

2023-11-21 13:43 UTC, JYisus commented on helm/kai/templates/engine/k8s-manager/configmap.yaml
> +  KAI_IMAGE_BUILDER_IMAGE: {{ .Values.k8sManager.imageBuilder.image }}
Done, I also changed tag and pullpolicy env vars and how they are defined in the values.yaml

2023-11-21 15:18 UTC, alexrodfe approved these changes

2023-11-21 15:40 UTC, alpiquero approved these changes

2023-11-22 08:04 UTC, dfinteligenz approved these changes

2023-11-22 09:43 UTC, merged