feat: add redis prediction database
konstellation-io/kai pull request #199
Opened 2023-11-23 10:54 UTC by JYisus

## Description

- Add prediction repository to admin api
- Add CreateUser to Redis prediction repository
- Create user in Redis when a product is created with the user account credentials
- Propagate ServiceAccount info on version start
- Set Redis configuration in SDKs configuration 
## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-11-27 08:17 UTC, dfinteligenz requested changes

2023-11-28 12:32 UTC, kafkaphoenix submitted a review, later dismissed

2023-11-29 08:01 UTC, kafkaphoenix submitted a review, later dismissed

2023-11-29 08:33 UTC, dfinteligenz requested changes

2023-11-29 08:33 UTC, dfinteligenz commented on engine/k8s-manager/internal/infrastructure/kube/configuration/create.go
> +			WorkflowType: workflow.Type,
Either add ToString() to the `workflow.Type`, or remove it from the `process.Type`

2023-11-29 10:08 UTC, JYisus commented on engine/k8s-manager/internal/infrastructure/kube/configuration/create.go
> +			WorkflowType: workflow.Type,
process.Type has a ToString because is defined as a ValueObject, I could define workflow type as a value object too

2023-11-29 15:00 UTC, kafkaphoenix submitted a review, later dismissed

2023-11-29 17:09 UTC, alexrodfe approved these changes

2023-11-29 23:23 UTC, dfinteligenz approved these changes

2023-11-30 09:12 UTC, merged