feat(helm): cleanup chart's unused components
konstellation-io/kai pull request #201
Opened 2023-11-23 15:44 UTC by IGZangelcostales

## Description
Remove the following components from the chart:

* Chronograf templates and values
* InfluxDB from chart’s dependencies and values
* Kapacitor from chart’s dependencies and values
* Mongo-Express from templates and values
* Credentials secrets for Mongo-Express in the local dev mongodb creation (helmfile)

Finally, move all the templates folders from the `engine` folder to the chart's root folder.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-11-24 08:42 UTC, alpiquero approved these changes

2023-11-24 09:12 UTC, dfinteligenz requested changes

2023-11-24 09:12 UTC, dfinteligenz commented on helm/kai/templates/mongo-writer/deployment.yaml
We should be able to remove the mongo-writer as we are not using it anymore.

2023-11-24 09:12 UTC, dfinteligenz commented on helm/kai/README.md
> +except for **minio** everything else is an optional dependency. To disable it during installation, set `<component_name>.enabled`, to `false`.
I'd add a bit more of context here.

The components are not optional, but externalizable. If disabled, the user needs to set the needed config for using these components from their infrastructure.

2023-11-24 12:42 UTC, dfinteligenz commented on helm/kai/templates/mongo-writer/deployment.yaml
https://github.com/konstellation-io/kai/pull/202

2023-11-27 12:49 UTC, IGZangelcostales commented on helm/kai/README.md
> +except for **minio** everything else is an optional dependency. To disable it during installation, set `<component_name>.enabled`, to `false`.
Done

2023-11-27 14:54 UTC, merged