feat(admin-api): add the option to deploy new versions with 0 downtime admin api
konstellation-io/kai pull request #239
Opened 2024-01-22 09:57 UTC by JYisus

## Description

- Make publish asynchronous
- Receive a new parameter 'force' in publish:
- If a version stopped is published and force is true, the version is started and then published
- If a product has another version published and force is true, the previous version is unpublished before publishing the new one

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2024-01-22 10:01 UTC, kafkaphoenix approved these changes

2024-01-22 11:24 UTC, dfinteligenz commented on engine/admin-api/domain/usecase/version/publish.go
> +}
I'd call them `PublishOpts` to maintain the same naming as in the rest of the repositories.

2024-01-24 08:23 UTC, kafkaphoenix submitted a review, later dismissed

2024-01-24 08:42 UTC, dfinteligenz requested changes
Great job @JYisus!
Just noticed a small typo.

2024-01-24 08:42 UTC, dfinteligenz commented on engine/admin-api/domain/usecase/version/publish.go
> +func (h *Handler) rollbackPublishVersionFunc(product *entity.Product, version *entity.Version) compensator.Compensation {
```suggestion
func (h *Handler) rollbackPublishedVersionFunc(product *entity.Product, version *entity.Version) compensator.Compensation {
```

2024-01-24 10:22 UTC, dfinteligenz approved these changes

2024-01-24 10:23 UTC, merged