Knt1 329 implement token parser package
konstellation-io/kai pull request #33
Opened 2023-05-12 07:54 UTC by dfinteligenz

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [x] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-05-16 06:43 UTC, dfinteligenz commented
@JYisus LGTM!

2023-05-18 08:24 UTC, dfinteligenz commented on engine/admin-api/delivery/http/token/claims.go
> +	RealmAccess   RealmAccess          `json:"realm_access"`
I'd replace realm_access for roles, the realm_access reference is from Keycloak.

2023-05-18 08:24 UTC, dfinteligenz commented on engine/admin-api/delivery/http/token/claims.go
> +type ProductRoles map[string][]string
```suggestion
type ProductGrants map[string][]string
```

2023-05-18 08:24 UTC, dfinteligenz commented on engine/admin-api/domain/usecase/product_interactor_test.go
> +func TestCreateNewProduct_FailsIfUserHasNotPermission(t *testing.T) {
```suggestion
func TestCreateNewProduct_FailsIfUserHasNoGrants(t *testing.T) {
```

2023-05-18 08:24 UTC, dfinteligenz commented on engine/admin-api/domain/usecase/product_interactor_test.go
> +	permissionError := errors.New("permission error")
```suggestion
	grantsError := errors.New("grants error")
```

2023-05-18 09:40 UTC, alexrodfe commented on engine/admin-api/adapter/auth/casbin_access_control.go
> +	return fmt.Errorf("you are not allowed to %s %s", action, product)
```suggestion
	return fmt.Errorf("you are not allowed to %q in product %q", action, product)
```

2023-05-18 09:42 UTC, alexrodfe commented on engine/admin-api/adapter/auth/casbin_access_control.go
> +	grants := args[0].(entity.ProductGrants)
we should check here if len of args is 3, just in case

2023-05-18 09:52 UTC, alexrodfe commented on engine/admin-api/delivery/http/middleware/auth.go
> +func extractToken(authHeader string) string {
This seems rather arbitrary, a function doc with an examples of the expected incoming headers could be very useful here

2023-05-18 09:58 UTC, alexrodfe commented on engine/admin-api/delivery/http/server_test.go
> +func TestServerCall(t *testing.T) {
If you are expecting an unauthorized status return, the naming of the test should reflect that

2023-05-18 10:17 UTC, alexrodfe requested changes
Great work!
I have some questions / suggestions, overall really good new feature

2023-05-18 13:04 UTC, JYisus commented on engine/admin-api/delivery/http/token/claims.go
> +	RealmAccess   RealmAccess          `json:"realm_access"`
We had to set the realm_access tag anyways to be able to parse it. Maybe we can add an extra abstraction layer add rename the struct to KeycloakCustomClaims

2023-05-18 16:20 UTC, JYisus commented on engine/admin-api/delivery/http/middleware/auth.go
> +func extractToken(authHeader string) string {
i can change the name of the function for something more explanatory instead

2023-05-19 10:36 UTC, alexrodfe approved these changes
Ship it :sunglasses:

2023-05-19 13:59 UTC, merged