feat(admin-api): new gocloak client, updated user usecase
konstellation-io/kai pull request #35
Opened 2023-05-12 13:02 UTC by alexrodfe

## Description

- Added new keycloak client
- Updated user usecase to use new keycloak client
- Added tests for usecase
- Updated graphql methods
- Deprecated previous access level related operations

## Motivation and Context

As now user management is maintained by keycloak, user related operations from api should be managed through a keycloak client.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [X] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-05-16 07:10 UTC, dfinteligenz requested changes

2023-05-16 07:10 UTC, dfinteligenz commented on engine/admin-api/domain/entity/user_activity.go
> +	UserActivityTypeCreateRuntime            UserActivityType = "CREATE_RUNTIME"
This should be changed to:

```suggestion
	UserActivityTypeCreateProduct            UserActivityType = "CREATE_PRODUCT"
```

2023-05-16 07:56 UTC, alexrodfe commented on engine/admin-api/domain/usecase/user.go
> +// UserInteractor talks to the gocloak service, thus providing user realted operations.
Agreed, I'll add an interface for the user usecase

2023-05-16 15:39 UTC, alexrodfe commented on engine/admin-api/adapter/gql/http_handler.go
> +	userInteractor usecase.UserInteractorUsecase,
change to struct pointer

2023-05-16 15:39 UTC, alexrodfe commented on engine/admin-api/adapter/gql/resolver.go
> +
return get by id

2023-05-16 17:26 UTC, JYisus commented
We should decide if we want to use `product permissions` or `product grants` as the naming @alexrodfe @dfinteligenz

2023-05-16 17:26 UTC, JYisus requested changes

2023-05-16 17:26 UTC, JYisus commented on engine/admin-api/domain/usecase/user_test.go
> +func (suite *ContextUserManagerSuite) TestGetUserByIDErrorInGocloak() {
avoid using gocloak in usecase tests names

2023-05-17 09:37 UTC, alexrodfe commented on engine/admin-api/domain/usecase/user_test.go
> +	suite.mockLogger.EXPECT().Infof(updateUserProductPermissionsLog, testUserData.ID, testProduct, permissions).Times(1)
Great tip! I'll add it to the tests

2023-05-17 09:52 UTC, alexrodfe commented on engine/admin-api/domain/usecase/user_test.go
> +func (suite *ContextUserManagerSuite) TestGetUserByIDErrorInGocloak() {
agreed, now that the service interface is called UserRegistry I'll use that as naming

2023-05-18 09:21 UTC, dfinteligenz approved these changes
Great job!

2023-05-18 09:36 UTC, merged