feat(admin-api): Use of new KRT
konstellation-io/kai pull request #57
Opened 2023-06-21 14:12 UTC by alexrodfe

## Description

- New version entity
- Migrated version repo
- Migrated version interacter
- New graphql schema
- New domain errors
- Updated testing
- Updated Service k8s and nats naming

## Motivation and Context

Following steps for new architecture migration, a new KRT structure depicting a new product architecture has been developed.
This PR applies the new KRT into the version related logic.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-06-27 01:15 UTC, JYisus requested changes

2023-06-27 01:15 UTC, JYisus commented on engine/admin-api/domain/entity/processlog.go
> +	ProcessID    string   `bson:"processId" gqlgen:"processId"`
Whats the difference between processID and processName?

2023-06-27 01:15 UTC, JYisus commented on engine/admin-api/domain/repository/version.go
> +	GetVersionsByProduct(ctx context.Context, productID string) ([]*entity.Version, error)
Maybe we should use ListVersionByProduct or ListByProduct instead of Get, since this returns multiple versions

2023-06-27 01:15 UTC, JYisus commented on engine/admin-api/domain/service/krt_mapper.go
> +package service
It's a bit weird to me having this mapper in the domain layer. Maybe the application layer is a better place for it.

2023-06-27 01:15 UTC, JYisus commented on engine/admin-api/domain/usecase/errors/errors.go
> +func Join(errs ...error) error {
This is redundant

2023-06-27 01:15 UTC, JYisus commented on engine/admin-api/test_assets/classificator_krt.yaml
> +name: email-classificator
The tests assets folder should be renamed to testdata. The go compiler ignores testdata folders.

2023-06-27 11:49 UTC, alexrodfe commented on engine/admin-api/adapter/gql/resolver.go
> +		if errors.Is(err, errors.ErrInvalidKRT) {
That is what is happening. Create method upon encountering krt validation errors invokes "InvalidKRTError" method which concatenates an ErrInvalidKRT with the validation errors.
This way, using 1.20 go errors we are able to do a errors.Is then having this error used later on in the gql error response.

2023-06-27 11:50 UTC, alexrodfe commented on engine/admin-api/adapter/repository/mongodb/version/entity.go
> +type ConfigurationVariable struct {
It doesnt, during testing I came across it and changed it to private

2023-06-27 11:50 UTC, alexrodfe commented on engine/admin-api/adapter/repository/mongodb/version/entity.go
> +	Key   string
Right, I forgot about those here hahaha

2023-06-27 12:36 UTC, JYisus commented on engine/admin-api/adapter/gql/resolver.go
> +		if errors.Is(err, errors.ErrInvalidKRT) {
Not exactly. You are defining a constant error that you are later checking. If you wrap this error, the errors.Is works fine, but could be sending to the user data that he doesn't care. With a custom type we can store just the validation messages and keep wraping for our internal error handling, and then just send to the user the validation errors.

2023-06-27 14:32 UTC, alexrodfe commented on engine/admin-api/adapter/repository/mongodb/version/repository.go
> +	usecaseErrors "github.com/konstellation-io/kai/engine/admin-api/domain/usecase/errors"
I feel like this choice will turn into a deep conversation about error handling in admin-api. So for the moment I'm renaming it to "apperrors" until we define a proper way to handle and declare errors.

2023-06-27 14:33 UTC, alexrodfe commented on engine/admin-api/adapter/repository/mongodb/version/entity.go
> +type ConfigurationVariable struct {
It could, and I did ask whether we wanted this to be a map or an array to be stored in the DB. No decision was made so I kept the array to follow suit with the rest of structures

2023-06-27 14:34 UTC, alexrodfe commented on engine/admin-api/domain/entity/processlog.go
> +	ProcessID    string   `bson:"processId" gqlgen:"processId"`
The process name is the name given to the process by the user through the krt.yaml file. The ID is the _id generated by mongoDB when storing the process.

2023-06-27 14:35 UTC, alexrodfe commented on engine/admin-api/domain/repository/version.go
> +	GetVersionsByProduct(ctx context.Context, productID string) ([]*entity.Version, error)
"ListVersionsByProduct" is a good fit :+1:

2023-06-27 14:54 UTC, alexrodfe commented on engine/admin-api/domain/usecase/errors/errors.go
> +func Join(errs ...error) error {
I know, but this allows me to use this errors package instead of importing the golangs native errors package then having to custom name the domain's errors package

2023-06-27 14:55 UTC, alexrodfe commented on engine/admin-api/test_assets/classificator_krt.yaml
> +name: email-classificator
I didn't know about that, I'm changing it to testdata then

2023-06-28 12:16 UTC, JYisus submitted a review, later dismissed

2023-06-28 12:21 UTC, JYisus approved these changes

2023-06-28 12:32 UTC, merged