feat: add support for multiple process types
konstellation-io/kai pull request #63
Opened 2023-06-29 01:55 UTC by JYisus

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-06-29 10:01 UTC, alexrodfe commented on engine/admin-api/adapter/service/k8smanager/mapper.go
> +func mapWorkflowsToDTO(workflows []entity.Workflow, versionConfig *entity.VersionConfig) ([]*versionpb.Workflow, error) {
having a test for this function in which we compare two hand made structures could be a great addition

2023-06-29 10:08 UTC, alexrodfe commented on engine/admin-api/adapter/service/k8smanager/mapper.go
> +	if len(config) == 0 {
can config be nil here?

2023-06-29 10:10 UTC, alexrodfe commented on engine/admin-api/adapter/service/nats.go
> +		VersionName: version.ID,
version.ID is the ID given by the MongoDB upon saving in DB. I believe we are looking for version.Name

2023-06-29 10:10 UTC, alexrodfe commented on engine/admin-api/adapter/service/nats.go
> +		VersionName: version.ID,
Same here

2023-06-29 10:12 UTC, alexrodfe commented on engine/admin-api/adapter/service/nats.go
> +func (n *NatsManagerClient) mapWorkflowsToDTO(workflows []entity.Workflow) ([]*natspb.Workflow, error) {
Could this func be moved to a mapper.go file?

2023-06-29 10:16 UTC, alexrodfe commented on engine/admin-api/adapter/service/nats.go
> +			nodeToAppend := natspb.Process{
watchout this variable and all following references to "node"

2023-06-29 10:19 UTC, JYisus commented on engine/admin-api/adapter/service/k8smanager/mapper.go
> +func mapWorkflowsToDTO(workflows []entity.Workflow, versionConfig *entity.VersionConfig) ([]*versionpb.Workflow, error) {
I think this function should be tested indirectly with another tests. Having tests for private functions is a code smell.

2023-06-29 10:23 UTC, JYisus commented on engine/admin-api/adapter/service/k8smanager/mapper.go
> +	if len(config) == 0 {
If its nil, len is 0

2023-06-29 10:27 UTC, alexrodfe commented on engine/admin-api/domain/entity/key_value_store_config.go
> +func (w *WorkflowKeyValueStores) GetNodeKeyValueStore(process string) (string, error) {
"GetNode"

2023-06-29 10:30 UTC, alexrodfe commented on engine/admin-api/domain/usecase/krt/krt_mapper_test.go
> +	"github.com/konstellation-io/krt/pkg/krt"
This is a personal preference but I like to have the imports in three blocks: native libraries then external libraries then internal libraries

2023-06-29 10:31 UTC, alexrodfe commented on engine/k8s-manager/.mockery.yaml
> +with-expecter: True
what is this for?

2023-06-29 10:34 UTC, alexrodfe commented on engine/k8s-manager/cmd/bootstrap/bootstrap.go
> +	port := 50051
why is this declared here instead of taken from config?

2023-06-29 10:46 UTC, alexrodfe commented on engine/k8s-manager/config.yml
> +# nats_streaming:
should we leave all this dead code here?

2023-06-29 11:07 UTC, alexrodfe commented on engine/k8s-manager/internal/infrastructure/grpc/version.go
> +	err := v.stopper.StopVersion(ctx, usecase.StopParams{
missing log here

2023-06-29 11:10 UTC, JYisus commented on engine/admin-api/domain/usecase/krt/krt_mapper_test.go
> +	"github.com/konstellation-io/krt/pkg/krt"
I also did that, but i have seen in many places the recomendation of having 2 groups following the goimports convention and its more comfortable because the IDE autoimports works better

2023-06-29 11:10 UTC, JYisus commented on engine/k8s-manager/.mockery.yaml
> +with-expecter: True
Is mockery configuration

2023-06-29 11:11 UTC, alexrodfe commented on engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.proto
> +  string message = 2;
this should be marked as 1

2023-06-29 11:22 UTC, alexrodfe commented on engine/k8s-manager/internal/application/service/container.go
> +		ctx context.Context,
I believe these don't need break lines

2023-06-29 11:25 UTC, alexrodfe commented on engine/admin-api/domain/usecase/krt/krt_mapper_test.go
> +	"github.com/konstellation-io/krt/pkg/krt"
In that case lets have it like that

2023-06-29 11:26 UTC, alexrodfe commented on engine/admin-api/adapter/service/k8smanager/mapper.go
> +	if len(config) == 0 {
Seems reasonable

2023-06-29 11:28 UTC, alexrodfe commented on engine/admin-api/adapter/service/k8smanager/mapper.go
> +func mapWorkflowsToDTO(workflows []entity.Workflow, versionConfig *entity.VersionConfig) ([]*versionpb.Workflow, error) {
being this private function the whole purpose of a file I don't see it like a code smell. In admin-api I tried to test this through an EXPECTS input then I noticed you will miss some translations, in my experience a dedicated test probed to be more specific an easier to make

2023-06-29 14:10 UTC, alexrodfe commented on engine/nats-manager/internal/manager/nats.go
This interface is not being used

2023-07-04 10:34 UTC, alexrodfe commented on engine/admin-api/adapter/service/natsmanager/mapper.go
> +		return natspb.ObjectStoreScope_SCOPE_WORKFLOW, errors.New("invalid object store scope")
I believe this error is never gonna happen. I'd rather have it gone so mapper functions are cleaner with no error return

2023-07-05 11:02 UTC, alexrodfe approved these changes
Incredible work, lets ship it :sunglasses:

2023-07-05 16:01 UTC, alexrodfe approved these changes

2023-07-06 05:59 UTC, dfinteligenz requested changes

2023-07-06 05:59 UTC, dfinteligenz commented on engine/k8s-manager/internal/domain/version.go
> +}
IMO this should not go on the domain object, I'd move this logic to the method where it's been used.
Also I would rename it to `getProcessAmount()`

2023-07-06 05:59 UTC, dfinteligenz commented on engine/k8s-manager/internal/infrastructure/kube/client.go
> +	kubeConfigPath := filepath.Join(os.Getenv("HOME"), ".kube", "config")
We could thing of having a configuration parameter on viper for defining the configuration file to be read, with the default values we have above.

2023-07-06 05:59 UTC, dfinteligenz commented on engine/nats-manager/internal/service/mapper.go
As a rule of thumb, always add the `map` prefix to mapping functions.

2023-07-06 13:41 UTC, alexrodfe commented on engine/admin-api/testhelpers/process_builder.go
> +package testhelpers
This test helper is being used in two different testing packages, should we duplicate the builder?

2023-07-06 15:44 UTC, closed without merging