fix(nats-manager): cleanup dots in version tag
konstellation-io/kai pull request #88
Opened 2023-08-14 11:27 UTC by alexrodfe

## Description

- Stream and key value store naming now cleanup dots in version tags.

## Motivation and Context

Naming in nats' resources cannot contain dots, so we are replacing dots introduced in version tags for underscores.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-08-14 11:28 UTC, kafkaphoenix approved these changes

2023-08-16 07:04 UTC, dfinteligenz requested changes
Good job @alexrodfe!
Check out the IT test errors and once you've got them, you can merge this.

2023-08-16 09:53 UTC, kafkaphoenix submitted a review, later dismissed

2023-08-16 10:23 UTC, dfinteligenz approved these changes

2023-08-16 10:36 UTC, kafkaphoenix approved these changes

2023-08-16 10:42 UTC, dfinteligenz approved these changes

2023-08-16 10:52 UTC, merged