feat: List process registry query
konstellation-io/kai pull request #91
Opened 2023-08-28 14:34 UTC by alexrodfe

## Description

Added query support for listing process registries.

## Motivation and Context

The second phase of process registries commands demands support for listing operations. Users will be able from kli to query through graphql process registries from a product. This query can have a process type filter.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [X] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-08-29 06:34 UTC, kafkaphoenix approved these changes

2023-08-29 06:53 UTC, dfinteligenz requested changes
Great job!
Just a pair of suggestions.

2023-08-29 06:53 UTC, dfinteligenz commented on engine/admin-api/adapter/gql/resolver.go
> +func (r *queryResolver) ProcessRegistries(ctx context.Context, productID string, processType *string) ([]*entity.ProcessRegistry, error) {
We are retrieving a list of processes (ore registered processes), not process registries.
I'd rename the method to reflect that.

```suggestion
func (r *queryResolver) RegisteredProcesses(ctx context.Context, productID string, processType *string) ([]*entity.ProcessRegistry, error) {
```

2023-08-29 06:53 UTC, dfinteligenz commented on engine/admin-api/domain/repository/process_registry.go
> +	ListByProductWithTypeFilter(ctx context.Context, productID, processType string) ([]*entity.ProcessRegistry, error)
Both product and type are filters for the query, I'd rename the method to `ListByProductAndType` to make it more clear.

```suggestion
	ListByProductAndType(ctx context.Context, productID, processType string) ([]*entity.ProcessRegistry, error)
```

2023-08-29 06:53 UTC, dfinteligenz commented on engine/admin-api/domain/usecase/process_service.go
> +		ps.logger.Error(ErrInvalidProcessReference, "%q, defaulting to use whole process reference", processRef)
As the default behavior is to return a default value, I'd replace the Error log with a Warn log instead.

2023-08-29 06:53 UTC, dfinteligenz commented on engine/admin-api/schema.graphql
> +  processRegistries(productID: ID!, processType: String): [ProcessRegistry]!
Ditto, I'd replace the method with `registeredProcesses`.

```suggestion
  registeredProcesses(productID: ID!, processType: String): [ProcessRegistry]!
```

2023-08-30 10:02 UTC, alexrodfe commented on engine/admin-api/domain/usecase/process_service.go
> +		ps.logger.Error(ErrInvalidProcessReference, "%q, defaulting to use whole process reference", processRef)
There is no logger.Warn so I'll use a Info with a "WARNING" in string

2023-08-31 10:41 UTC, JYisus approved these changes

2023-08-31 11:38 UTC, dfinteligenz commented on engine/admin-api/domain/usecase/process_service.go
> +		ps.logger.Error(ErrInvalidProcessReference, "%q, defaulting to use whole process reference", processRef)
You need to add a V(2) if I'm not mistaken so that the level of the logger is WARN.

2023-08-31 11:41 UTC, dfinteligenz approved these changes

2023-08-31 11:45 UTC, merged