Feature/start version
konstellation-io/kai pull request #99
Opened 2023-09-12 15:50 UTC by alexrodfe

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-09-12 16:06 UTC, kafkaphoenix submitted a review, later dismissed

2023-09-13 10:43 UTC, kafkaphoenix submitted a review, later dismissed

2023-09-13 12:00 UTC, JYisus commented on engine/admin-api/domain/usecase/version/create.go
> +	// TODO: fix me
Is this to do necessary? If its possible fix it or open a technical debt task

2023-09-13 14:38 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/create.go
> +	// TODO: fix me
Done, it is: https://intelygenz.atlassian.net/browse/KNT1-493

2023-09-14 11:10 UTC, JYisus requested changes

2023-09-14 11:10 UTC, JYisus commented on engine/admin-api/domain/usecase/version/start.go
> +		h.logger.Error(ErrRegisteringUserActivity, "ERROR",
The second param in errors should be an explicative message, if the string is ERROR, the log will be something like
```
2023-09-14T12:00:05.238+0100	ERROR	testing/main.go:22	ERROR	{"error": ...}
```
which is redundant

2023-09-14 11:10 UTC, JYisus commented on engine/admin-api/domain/usecase/version/start.go
> +		h.logger.Error(ErrRegisteringUserActivity, "ERROR",
Same here

2023-09-14 11:10 UTC, JYisus commented on engine/admin-api/domain/usecase/version/start.go
> +			"versionError", startErr.Error(),
Instead of doing this, the error should be the first param of the function

2023-09-14 11:10 UTC, JYisus commented on engine/admin-api/domain/usecase/version/start_test.go
> +		fmt.Errorf("git good"),
Instead of this, declare a variable "expectedError" and initialize it with errors.New (fmt.Errorf should be used only when wrapping messages).
Then, you can check if this error is in the error chain returned by the usecase with and ErrorIs assert.

2023-09-14 11:10 UTC, JYisus commented on engine/admin-api/domain/usecase/version/start_test.go
> +		fmt.Errorf("git good"),
This could be applied to all the error tests.

2023-09-14 11:10 UTC, JYisus commented on engine/admin-api/domain/usecase/version/utils/testutil_version.go
> +package utils
The version builder already exists in the testhelpers package.

2023-09-15 14:11 UTC, alexrodfe commented on engine/admin-api/domain/entity/version.go
>  func (v Version) PublishedOrStarted() bool {
deleted due to unused

2023-09-15 14:11 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/start.go
> +		h.registerStartActionFailed(user.ID, productID, v, CommentUserNotAuthorized)
agreed, I'll change it

2023-09-15 14:12 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/start.go
> +		h.logger.Error(ErrUpdatingVersionStatus, "CRITICAL",
we want it to be non blocking

2023-09-15 14:12 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/start.go
> +		h.logger.Error(ErrRegisteringUserActivity, "ERROR",
agreed, I'll change it

2023-09-15 14:12 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/start.go
> +			"versionError", startErr.Error(),
I agree, it has been changed

2023-09-15 14:12 UTC, alexrodfe commented on engine/admin-api/domain/usecase/version/start_test.go
> +		fmt.Errorf("git good"),
Good idea! I'll change it

2023-09-15 14:40 UTC, JYisus submitted a review, later dismissed

2023-09-15 14:42 UTC, JYisus approved these changes

2023-09-15 14:43 UTC, kafkaphoenix approved these changes

2023-09-15 14:47 UTC, kafkaphoenix approved these changes

2023-09-15 14:47 UTC, JYisus approved these changes

2023-09-15 14:54 UTC, merged